title: Australian Tree of Life Documentation
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Australian Tree of Life
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Documentation and technical information describing the Australian Tree of Life project"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@5.0.0

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/Australian-Biocommons-Logo-Horizontal-RGB.png

exclude:
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
